apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-handson
spec:
  selector:
    matchLabels:
      app: argocd-handson
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-handson
    spec:
      containers:
      - name: argocd-handson
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
